context:
    id: 12345
    complete: false
    errors: false
    late: false
    month: October
    framework:
      short_name: 'RM0000'
      name: 'Framework name'
      supplier_name: 'Supplier ABC'
